version: "3.8"

services:
	
  configserver:
    image: configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - lockin-network

  accounts:
    image: accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - lockin-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  loans:
    image: loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - lockin-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  cards:
    image: cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - lockin-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
networks:
  lockin-network:
